# Generated by Django 6.0.2 on 2026-02-21 22:37

from django.db import migrations


def create_roles(apps, schema_editor):
    Rol = apps.get_model("users", "Rol")

    roles = [
        "DUENO",
        "ADMINISTRADOR",
        "TRABAJADOR",
    ]

    for rol in roles:
        Rol.objects.get_or_create(nombre=rol)


def reverse_roles(apps, schema_editor):
    Rol = apps.get_model("users", "Rol")
    Rol.objects.filter(
        nombre__in=[
            "DUENO",
            "ADMINISTRADOR",
            "TRABAJADOR",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_code=reverse_roles),
    ]
