# Generated by Django 6.0.2 on 2026-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nombre",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
