# Generated by Django 6.0.2 on 2026-02-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_usuario_activo_remove_usuario_apellido_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="created",
        ),
    ]
