# Generated by Django 6.0.2 on 2026-02-16 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usuario_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotienda',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
