# Generated by Django 6.0.2 on 2026-02-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_initial'),
        ('users', '0004_alter_usuariotienda_salario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuariotienda',
            constraint=models.CheckConstraint(condition=models.Q(('salario__gte', 0)), name='salario_non_negative'),
        ),
    ]
