# Generated by Django 6.0.2 on 2026-02-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_initial'),
        ('users', '0005_usuariotienda_salario_non_negative'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariotienda',
            unique_together={('usuario', 'tienda')},
        ),
    ]
