# Generated by Django 6.0.2 on 2026-02-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuariotienda_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('usuario_tienda', 'fecha')},
        ),
    ]
