# Generated by Django 6.0.2 on 2026-02-17 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_asistencia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotienda',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
