# Generated by Django 6.0.2 on 2026-02-19 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuariotienda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotienda',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL),
        ),
    ]
