# Generated by Django 6.0.2 on 2026-02-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
