# Generated by Django 6.0.2 on 2026-02-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("servicios", "0001_initial"),
        ("tiendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="tienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicios",
                to="tiendas.tienda",
            ),
        ),
    ]
