# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='usuario_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuariotienda'),
        ),
    ]
