# Generated by Django 6.0.2 on 2026-02-12 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tiendas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="id_duenio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiendas_duenio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
