# Generated by Django 6.0.2 on 2026-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_llegada", models.DateField()),
                (
                    "costo_operacion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "costo_transporte",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoteProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_inicial", models.PositiveIntegerField()),
                ("cantidad_actual", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_venta_base",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
