# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.lote'),
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='loteproducto',
            unique_together={('lote', 'producto')},
        ),
    ]
