# Generated by Django 6.0.2 on 2026-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0002_initial'),
        ('users', '0008_alter_usuariotienda_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAGADA', 'Pagada')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_pago', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GastoVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=225)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('monto_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('CORRECTO', 'Correcto'), ('PENDIENTE', 'Pendiente')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='tiendas.tienda')),
                ('usuario_tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.usuariotienda')),
            ],
        ),
    ]
