# Generated by Django 6.0.2 on 2026-02-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('tiendas', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='ventas.cliente'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deuda', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='gastofijo',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_fijos', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='gastovariable',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_variables', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='pagodeuda',
            name='deuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.deuda'),
        ),
    ]
