# Generated by Django 6.0.2 on 2026-02-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='tiendas.tienda'),
        ),
    ]
